2023-06-09T17:22:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "/home/smogan/Berkeley/Research/quantum-sensing/quantum_sensing/fancy_microscope/test_app.py", line 144, in <module>
    app = ImageTestApp(sys.argv)
  File "/home/smogan/.local/lib/python3.10/site-packages/ScopeFoundry/base_app.py", line 351, in __init__
    self.setup()
  File "/home/smogan/Berkeley/Research/quantum-sensing/quantum_sensing/fancy_microscope/test_app.py", line 18, in setup
    self.add_measurement(TestMeasure(self))
  File "/home/smogan/.local/lib/python3.10/site-packages/ScopeFoundry/measurement.py", line 107, in __init__
    self.setup()
  File "/home/smogan/Berkeley/Research/quantum-sensing/quantum_sensing/fancy_microscope/test_app.py", line 46, in setup
    self.ui.plotting_type.cb = cb = QComboBox()
NameError: name 'QComboBox' is not defined

