2023-06-09T15:33:50|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "/home/smogan/Berkeley/Research/quantum-sensing/quantum_sensing/fancy_microscope/test_app.py", line 123, in <module>
    app = ImageTestApp(sys.argv)
  File "/home/smogan/.local/lib/python3.10/site-packages/ScopeFoundry/base_app.py", line 353, in __init__
    self.setup_default_ui()
  File "/home/smogan/.local/lib/python3.10/site-packages/ScopeFoundry/base_app.py", line 393, in setup_default_ui
    measure.setup_figure()
  File "/home/smogan/Berkeley/Research/quantum-sensing/quantum_sensing/fancy_microscope/test_app.py", line 46, in setup_figure
    self.ui.plot_groupBox.layout().addWidget(self.graph_layout)
AttributeError: 'TestMeasure' object has no attribute 'ui'

