2022-03-31T14:46:52|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\Users\Public\quantum_sensing\quantum_sensing\fancy_microscope\thorcam_sci\thorcam_sci_liveview.py", line 31, in run
    self._image_queue = queue.Queue(maxsize=2)
NameError: name 'queue' is not defined

2022-03-31T14:46:52|ERROR|ThorcamSCILiveView|thorcam_sci_live Failed to update figure1: name 'queue' is not defined. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_sci\\thorcam_sci_liveview.py", line 59, in update_display\n    image = self.image_queue.get_nowait()\n', "AttributeError: 'ThorcamSCILiveView' object has no attribute 'image_queue'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\ScopeFoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_sci\\thorcam_sci_liveview.py", line 70, in update_display\n    except queue.Empty:\n', "NameError: name 'queue' is not defined\n"]
2022-03-31T15:04:51|ERROR|FancyMicroscopeApp|tried to disconnect thorcam_sci: 'TLCameraSDK' object has no attribute 'close'
