2022-05-20T15:20:05|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "fancy_microscope.py", line 46, in <module>
    app = FancyMicroscopeApp(sys.argv)
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "fancy_microscope.py", line 31, in setup
    self.add_measurement(ESRMeasure(self))
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\Public\quantum_sensing\quantum_sensing\fancy_microscope\custommeasure2.py", line 35, in setup
    self.settings.Vpp.setDecimals(4)
AttributeError: 'LoggedQuantity' object has no attribute 'setDecimals'

