2022-03-30T12:58:45|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\site-packages\thorlabs_tsi_sdk\tl_camera.py", line 177, in __init__
    self._sdk = cdll.LoadLibrary(r"thorlabs_tsi_camera_sdk.dll")
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Public\quantum_sensing\quantum_sensing\fancy_microscope\thorcam_sci\thorcam_sci_hw.py", line 14, in connect
    self.sdk = TLCameraSDK()
  File "C:\Users\ZHao\.conda\envs\ScopeFoundry\lib\site-packages\thorlabs_tsi_sdk\tl_camera.py", line 185, in __init__
    "\nUnable to load library - are the thorlabs tsi camera sdk libraries "
thorlabs_tsi_sdk.tl_camera.TLCameraError: [WinError 126] The specified module could not be found
Unable to load library - are the thorlabs tsi camera sdk libraries discoverable from the application directory? Try placing them in the same directory as your program, or adding the directory with the libraries to the PATH. Make sure to use 32-bit libraries when using a 32-bit python interpreter and 64-bit libraries when using a 64-bit interpreter.


