2022-10-06T14:26:20|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'average_x'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 307, in update_display\n    self.current_plotline.setData(self.average_x[:self.cutoff], self.average_y[:self.cutoff])\n', "AttributeError: 'ESRMeasure' object has no attribute 'average_x'\n"]
2022-10-06T14:26:20|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'average_x'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 307, in update_display\n    self.current_plotline.setData(self.average_x[:self.cutoff], self.average_y[:self.cutoff])\n', "AttributeError: 'ESRMeasure' object has no attribute 'average_x'\n"]
2022-10-06T14:27:41|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\helper_funcs.py", line 93, in eventFilter
    def eventFilter(self, obj, event):
KeyboardInterrupt

2022-10-06T14:27:43|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\helper_funcs.py", line 93, in eventFilter
    def eventFilter(self, obj, event):
KeyboardInterrupt

