2022-10-26T15:50:18|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\Users\Public\quantum_sensing\quantum_sensing\fancy_microscope\thorcam_sci\thorcam_sci_hw.py", line 79, in disconnect
    self.cam.dispose()
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\thorlabs_tsi_sdk\tl_camera.py", line 529, in dispose
    error_code = self._sdk.tl_camera_disarm(self._camera)
KeyboardInterrupt

2022-10-26T15:50:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "fancy_microscope.py", line 48, in <module>
    app = FancyMicroscopeApp(sys.argv)
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "fancy_microscope.py", line 34, in setup
    self.add_measurement(ThorCamCaptureMeasure(self))
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\Public\quantum_sensing\quantum_sensing\fancy_microscope\thorcam_capture.py", line 203, in setup
    S['exp_time'] = 50
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 1153, in __setitem__
    self._logged_quantities[key].update_value(item)
KeyError: 'exp_time'

