2023-06-02T17:08:34|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "image_test_app.py", line 126, in <module>
    app = ImageTestApp(sys.argv)
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "image_test_app.py", line 18, in setup
    self.add_measurement(ImageMeasure(self))
  File "C:\Users\ZHao\.conda\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "image_test_app.py", line 54, in setup
    S.x_min.connect_to_widget(self.ui.x_min_doubleSpinBox)
AttributeError: 'LQCollection' object has no attribute 'x_min'

